### ISSUE TITLE
Modificar layout y template para ver una publicación o página

### ISSUE THREAD

**Issue by moudev** [svconectado/website#17]
# Descripción

- Hacer modificación de layout y template encargados de visualizar una publicación
- La tarea consiste que los elementos HTML tengan su propio estilo, podría servir que se cree un archivo css solo para agregar el estilo necesario a los elementos que sirvan para mostrar una publicación y, que solo sean agregados a una clase en especifico, ésta clase está asignada al contenedor que contiene todo el contenido HTML que devuelve wordpress

- **Ejemplo**;

**File**:  `layoutPublications.css`
**Content**: 
```scss
.container-content-wp-publications {
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    line-height: 1.5;
    @apply font-raleway font-medium;
    @apply mt-5 mb-4;
  }

  h1,
  h2 {
    @apply border-b border-divContainer;
  }

  h1 {
    @apply text-3xl;
  }
}
```
- **NOTA**: Sí se quiere dejar un archivo `.scss` con todas los estilos para las publicaciones, se tiene que instalar lo necesario para que gatsby pueda "convertir" los archivos y se pueda usar `TailwindCSS`. Más información en [Gatsby + TailwindCSS: Option #3: SCSS](https://www.gatsbyjs.org/docs/tailwind-css/#option-3-scss)
